service: frigg

provider:
  name: aws
  runtime: nodejs6.10
  stage: local
  environment:
    GITHUB_TOKEN: ${opt:githubToken}
    LOG_LEVEL:
      Fn::FindInMap: [ LogLevel, '${opt:stage, self:provider.stage}', level ]
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource:
        Fn::Join:
          - ':'
          - - 'arn:aws:sns'
            - Ref: AWS::Region
            - Ref: AWS::AccountId
            - '*'

functions:

  GitHubEventHandler:
    handler: github/webhook.handler
    events:
      - http:
          path: github
          method: post
          cors: true
    environment:
      CREATE_PIPELINE_TOPIC: { Ref: 'SNSTopicModifypipeline${opt:stage, self:provider.stage}' }
      GITHUB_WEBHOOK_SECRET:
        Fn::Join:
          - '-'
          - - '${opt:stage, self:provider.stage}'
            - Ref: AWS::AccountId

  # TODO change function to handle removing pipelines as well based on params
  ModifyPipeline:
    handler: pipelines/modify.handler
    timeout: 300 # 5 minutes
    events:
      - sns: modify-pipeline-${opt:stage, self:provider.stage}
    # Admin role needed for deploying serverless applications
    role: AdminDeployRole

resources:
  Description: Automated service for managing CodePipelines for repos & branches inside a GitHub organization

  Mappings:
    LogLevel:
      test:
        level: TRACE
      local:
        level: TRACE
      automation:
        level: INFO
      production:
        level: INFO
  
  Resources:
    # TODO DynamoDB table for storing pipeline information - which exist, build status, etc.

    AdminDeployRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: FriggAdminDeployAccess-${opt:stage, self:provider.stage}
            PolicyDocument:
              Version: '2012-10-17'
              Statement: 
                - Effect: Allow
                  Action: '*'
                  Resource: '*'
