service: frigg

provider:
  name: aws
  runtime: nodejs6.10
  stage: local
  environment:
    LOG_LEVEL:
      Fn::FindInMap: [ LogLevel, '${opt:stage, self:provider.stage}', level ]
    GITHUB_WEBHOOK_SECRET: poop
  iamRole:
    - Effect: Allow
      Resource: '*'
      Action: '*'

functions:

  GitHubEventHandler:
    handler: github.handler
    events:
      - http:
          path: github
          method: post
          cors: true

  CheckPipelineStatus:
    handler: handler.hello
    events:
      - sns: check-pipeline-status-${opt:stage, self:provider.stage}

  UpsertPipeline:
    handler: handler.hello
    events:
      - sns: upsert-pipeline-${opt:stage, self:provider.stage}

  RemovePipeline:
    handler: handler.hello
    events:
      - sns: remove-pipeline-${opt:stage, self:provider.stage}

resources:
  Description: Automated service for creating CodePipelines for applications inside a GitHub organization

  Mappings:
    LogLevel:
      test:
        level: TRACE
      local:
        level: TRACE
      automation:
        level: INFO
      production:
        level: INFO
