service: frigg

provider:
  name: aws
  runtime: nodejs6.10
  stage: local
  environment:
    GITHUB_TOKEN: ${opt:githubToken}
    LOG_LEVEL:
      Fn::FindInMap: [ LogLevel, '${opt:stage, self:provider.stage}', level ]
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource:
        Fn::Join:
          - ':'
          - - 'arn:aws:sns'
            - Ref: AWS::Region
            - Ref: AWS::AccountId
            - '*'

functions:

  WebhookHandler:
    handler: webhooks/handler.github
    events:
      - http:
          path: github
          method: post
          cors: true
    environment:
      UPSERT_PIPELINE_TOPIC: { Ref: 'SNSTopicUpsertpipeline${opt:stage, self:provider.stage}' }
      REMOVE_PIPELINE_TOPIC: { Ref: 'SNSTopicRemovepipeline${opt:stage, self:provider.stage}' }
      REMOVE_REPOSITORY_PIPELINES_TOPIC: { Ref: 'SNSTopicRemoverepositorypipelines${opt:stage, self:provider.stage}' }
      GITHUB_WEBHOOK_SECRET:
        Fn::Join:
          - '-'
          - - '${opt:stage, self:provider.stage}'
            - Ref: AWS::AccountId

  UpsertPipeline:
    handler: pipelines/handler.upsert
    timeout: 300 # 5 minutes
    events:
      - sns: upsert-pipeline-${opt:stage, self:provider.stage}
    role: ServerlessAdminRole # Admin role needed for deploying serverless applications

  RemovePipeline:
    handler: pipelines/handler.removePipeline
    events:
      - sns: remove-pipeline-${opt:stage, self:provider.stage}
    environment:
      ODIN_REMOVE_STACK_TOPIC: ${cf:odin-${opt:stage, self:provider.stage}.DeleteStackSNS}
    role: ServerlessAdminRole # Admin role needed for removing serverless applications

  RemoveRepositoryPipelines:
    handler: pipelines/handler.removeRepository
    events:
      - sns: remove-repository-pipelines-${opt:stage, self:provider.stage}
    environment:
      ODIN_REMOVE_STACK_TOPIC: ${cf:odin-${opt:stage, self:provider.stage}.DeleteStackSNS}
    role: ServerlessAdminRole # Admin role needed for removing serverless applications

resources:
  Description: Automated service for managing CodePipelines for repos & branches inside a GitHub organization

  Mappings:
    LogLevel:
      test:
        level: debug
      local:
        level: debug
      automation:
        level: info
      production:
        level: info
  
  Resources:

    ServerlessAdminRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: FriggAdminDeployAccess-${opt:stage, self:provider.stage}
            PolicyDocument:
              Version: '2012-10-17'
              Statement: 
                - Effect: Allow
                  Action: '*'
                  Resource: '*'
    
    PipelinesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: repository
            AttributeType: S
          - AttributeName: branch
            AttributeType: S
        KeySchema:
          - AttributeName: repository
            KeyType: HASH
          - AttributeName: branch
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
