version: 0.2

env:
  variables:
    STAGE: placeholder
    PIPELINE_SERVICE_NAME: placeholder
    REPO_NAME: placeholder
    OWNER: placeholder
    REPO: placeholder
    BRANCH: placeholder

phases:
  install:
    commands:
      - echo "nothing to install"
  
  pre_build:
    commands:
      - npm i
      - npm i -g serverless

  build:
    commands:
      - serverless deploy --stage $STAGE

  post_build:
    commands:
      - echo "build completed"
